FROM continuumio/anaconda3:latest
RUN apt-get update -qq
RUN apt-get install -y build-essential gcc libgsl0-dev sudo cpio libpango1.0-0
RUN apt-get install libasound2 libasound2-dev vim
RUN conda install -y -c conda-forge nlopt jupyter_contrib_nbextensions
RUN useradd -ms /bin/bash docker && echo "docker:docker" | chpasswd && adduser docker sudo
USER docker
WORKDIR /home/docker
RUN jupyter notebook --generate-config
# set jupyter notebook password as docker
RUN echo "c.NotebookApp.password='sha1:38583b94e9af:7a111623fd788790aba3ef1e3bb2779f62d58549'">>/home/docker/.jupyter/jupyter_notebook_config.py
